// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
//import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// import 'package:flutter/foundation.dart'
//     show defaultTargetPlatform, kIsWeb, TargetPlatform;
//
// /// Default [FirebaseOptions] for use with your Firebase apps.
// ///
// /// Example:
// /// ```dart
// /// import 'firebase_options.dart';
// /// // ...
// /// await Firebase.initializeApp(
// ///   options: DefaultFirebaseOptions.currentPlatform,
// /// );
// /// ```
// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//     if (kIsWeb) {
//       throw UnsupportedError(
//         'DefaultFirebaseOptions have not been configured for web - '
//         'you can reconfigure this by running the FlutterFire CLI again.',
//       );
//     }
//     switch (defaultTargetPlatform) {
//       case TargetPlatform.android:
//         return android;
//       case TargetPlatform.iOS:
//         return ios;
//       case TargetPlatform.macOS:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for macos - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       case TargetPlatform.windows:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for windows - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       case TargetPlatform.linux:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for linux - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       default:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions are not supported for this platform.',
//         );
//     }
//   }

  // static const FirebaseOptions android = FirebaseOptions(
  //   apiKey: 'AIzaSyA1__M314M8iEyFxQ9LpF-jYfL5fTxugrU',
  //   appId: '1:776234242790:android:09e9c00592313d2b9ce127',
  //   messagingSenderId: '776234242790',
  //   projectId: 'virtualfitnessph-579eb',
  //   storageBucket: 'virtualfitnessph-579eb.appspot.com',
  // );
  //
  // static const FirebaseOptions ios = FirebaseOptions(
  //   apiKey: 'AIzaSyC0MzLa4Rm6UW4BH4xmAlppqolBbem-PBc',
  //   appId: '1:776234242790:ios:677e9412ae46f8d89ce127',
  //   messagingSenderId: '776234242790',
  //   projectId: 'virtualfitnessph-579eb',
  //   storageBucket: 'virtualfitnessph-579eb.appspot.com',
  //   iosBundleId: 'com.vfph.virtualfitnessph',
  // );
//}
